### ISSUE TITLE
Hi,I found a SQL error in 'opencx/cxdb/cxdbsql/depositstore.go' line 38.

### ISSUE THREAD

**Issue by nightfallsad** [mit-dci/opencx#33]
When I run 'go build ./cmd/opencxd/...'  and executed './opencxd',it threw an error 
![image](https://user-images.githubusercontent.com/23025607/62134877-d7ee9b00-b313-11e9-84d6-b252cffcc672.png).
I think its because this code is incorrect,the two 'pubkey' isn't match.
 'depositAddrStoreSchema    = "pubkey VARBINARY(66), address VARCHAR(34), CONSTRAINT unique_pubkeys UNIQUE (pubkeys, address)"'

**Comment by Rjected** [comment]
Hi @nightfallsad, good catch! That's definitely a bug, can I see what the rest of the error said? I also can't reproduce it, do you have any more information, like your OS, and which database you're using (mariadb vs mysql etc.)?

**Comment by nightfallsad** [comment]
Hi @Rjected ,I changed the code 'depositAddrStoreSchema = "pubkey VARBINARY(66), address VARCHAR(34), CONSTRAINT unique_pubkeys UNIQUE (pubkeys, address)' to 'depositAddrStoreSchema = "pubkey VARBINARY(66), address VARCHAR(34), CONSTRAINT unique_pubkeys UNIQUE (**pubkey**, address)'.The problem was resolved.
